-- Seed File: seed_verified_safety_rules.sql
-- Description: Verified Clinical Safety Rules Seeded Directly from Verified EDA Formulary Monograph Citations
-- ONLY rules with final_verification_status = 'VERIFIED' (Passing 100% of the 5 Direct-Support Tests) are included.

INSERT INTO public.verified_safety_rules (
    id,
    rule_type,
    drug_a,
    drug_b,
    condition_name,
    allergen_class,
    dosage_form,
    status,
    reason,
    source_file,
    source_page,
    source_monograph,
    source_section,
    evidence_excerpt,
    source_authority,
    verified,
    active
) VALUES
-- 1. Dexamethasone + Diabetes Mellitus (Endocrine Formulary P.153)
(
    '00000000-0000-0000-0001-000000000001',
    'drug_disease',
    'dexamethasone',
    NULL,
    'diabetes_mellitus',
    NULL,
    NULL,
    'caution',
    'Systemic corticosteroids cause hyperglycemia and impair glycemic control in diabetic patients.',
    'egypt_endocrine_formulary_2024.pdf',
    153,
    'Dexamethasone',
    'Adverse Drug Reactions / Endocrine & Metabolic',
    'Dexamethasone ... Hyperglycemia: may provoke new-onset hyperglycemia in patients without a history of diabetes and may cause an exacerbation of diabetes mellitus.',
    'Egyptian Drug Authority',
    true,
    true
),
-- 2. Propranolol + Asthma (Cardiovascular Formulary P.122)
(
    '00000000-0000-0000-0001-000000000002',
    'drug_disease',
    'propranolol',
    NULL,
    'asthma',
    NULL,
    NULL,
    'contraindicated',
    'Non-selective beta-blockers cause bronchospasm and are contraindicated in asthma or severe obstructive airway disease.',
    'egypt_cardiovascular_formulary_2024.pdf',
    122,
    'Propranolol',
    'Contraindications',
    'Propranolol ... Contraindications: Asthma or severe chronic obstructive pulmonary disease; sinus bradycardia; cardiogenic shock.',
    'Egyptian Drug Authority',
    true,
    true
),
-- 3. Sildenafil + Isosorbide Dinitrate / Nitrates (Cardiovascular Formulary P.69)
(
    '00000000-0000-0000-0001-000000000003',
    'drug_drug',
    'sildenafil',
    'nitroglycerin',
    NULL,
    NULL,
    NULL,
    'contraindicated',
    'Co-administration of PDE5 inhibitors with organic nitrates causes severe refractory systemic hypotension.',
    'egypt_cardiovascular_formulary_2024.pdf',
    69,
    'Isosorbide Dinitrate',
    'Contraindications',
    'Isosorbide dinitrate ... Contraindications: Hypersensitivity to Isosorbide dinitrate or any component of the formulation; Concurrent use with phosphodiesterase inhibitors (Sildenafil, Tadalafil, Vardenafil, or Avanafil); Severe anemia.',
    'Egyptian Drug Authority',
    true,
    true
),
-- 4. Clarithromycin + Simvastatin (Antimicrobial Formulary P.185)
(
    '00000000-0000-0000-0001-000000000004',
    'drug_drug',
    'clarithromycin',
    'simvastatin',
    NULL,
    NULL,
    NULL,
    'contraindicated',
    'Macrolide inhibition of CYP3A4 metabolism of simvastatin dramatically increases the risk of severe rhabdomyolysis.',
    'egypt_antimicrobial_formulary_2023.pdf',
    185,
    'Clarithromycin',
    'Contraindications',
    'Clarithromycin ... Contraindications: Concomitant administration with astemizole, cisapride, pimozide, terfenadine, or lovastatin/simvastatin (risk of rhabdomyolysis).',
    'Egyptian Drug Authority',
    true,
    true
),
-- 5. High Alert - Insulins All Formulations (High Alert List P.10)
(
    '00000000-0000-0000-0001-000000000005',
    'high_alert',
    'insulin',
    NULL,
    NULL,
    NULL,
    'Insulins (All Formulations)',
    'warning',
    'High-Alert Medication: Insulins carry a heightened risk of causing severe hypoglycemia when miscalculated or incorrectly timed.',
    'egypt_high_alert_medications_2025.pdf',
    10,
    'High Alert Medication List in Community/Ambulatory Care Settings',
    'High Alert Medication List in Community/Ambulatory Care Settings',
    '1 Insulin, all formulations, all routes of administration (e.g., Subcutaneous, IV).',
    'Egyptian Drug Authority',
    true,
    true
),
-- 6. High Alert - Low Molecular Weight Heparins / Enoxaparin (High Alert List P.6)
(
    '00000000-0000-0000-0001-000000000006',
    'high_alert',
    'enoxaparin',
    NULL,
    NULL,
    NULL,
    'Antithrombotic agents (LMWH)',
    'warning',
    'High-Alert Medication: Anticoagulants carry a heightened risk of major hemorrhage; dosage verification and monitoring required.',
    'egypt_high_alert_medications_2025.pdf',
    6,
    'High Alert Medication List in Acute Care',
    'High Alert Medication List in Acute Care',
    '6 Antithrombotic agents Examples: Low molecular weight heparin (Enoxaparin), Unfractionated heparin IV, Direct thrombin inhibitors.',
    'Egyptian Drug Authority',
    true,
    true
),
-- 7. High Alert - Chemotherapy (Capecitabine / Cyclophosphamide) (High Alert List P.11)
(
    '00000000-0000-0000-0001-000000000007',
    'high_alert',
    'capecitabine',
    NULL,
    NULL,
    NULL,
    'Chemotherapeutic agents',
    'warning',
    'High-Alert Medication: Cytotoxic chemotherapy requires specialized oncology verification and precise dosing safeguards.',
    'egypt_high_alert_medications_2025.pdf',
    11,
    'High Alert Medication List in Community/Ambulatory Care Settings',
    'High Alert Medication List in Community/Ambulatory Care Settings',
    '2 Chemotherapeutic agents, excluding hormonal therapy: Oral and parenteral chemotherapy (e.g., capecitabine, cyclophosphamide).',
    'Egyptian Drug Authority',
    true,
    true
),
-- 8. Allergy - Amoxicillin in Beta-Lactam / Penicillin Hypersensitivity (Antimicrobial Formulary P.371)
(
    '00000000-0000-0000-0001-000000000008',
    'allergy',
    'amoxicillin',
    NULL,
    NULL,
    'penicillin',
    NULL,
    'contraindicated',
    'Amoxicillin is contraindicated in patients with documented hypersensitivity to penicillins or other beta-lactams.',
    'egypt_antimicrobial_formulary_2023.pdf',
    371,
    'Amoxicillin',
    'Contraindications',
    'Amoxicillin ... Contraindications: Serious hypersensitivity to amoxicillin or to other beta-lactams, or any component of the formulation.',
    'Egyptian Drug Authority',
    true,
    true
),
-- 9. Allergy - Sulfamethoxazole in Sulfonamide Hypersensitivity (Antimicrobial Formulary P.346)
(
    '00000000-0000-0000-0001-000000000009',
    'allergy',
    'sulfamethoxazole',
    NULL,
    NULL,
    'sulfonamides',
    NULL,
    'contraindicated',
    'Sulfamethoxazole is contraindicated in patients with known hypersensitivity to sulfonamides or trimethoprim.',
    'egypt_antimicrobial_formulary_2023.pdf',
    346,
    'Sulfamethoxazole and Trimethoprim',
    'Contraindications',
    'Sulfamethoxazole and Trimethoprim ... Contraindications: Hypersensitivity to trimethoprim or sulfonamides, or any component of the formulation.',
    'Egyptian Drug Authority',
    true,
    true
)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    reason = EXCLUDED.reason,
    source_file = EXCLUDED.source_file,
    source_page = EXCLUDED.source_page,
    source_monograph = EXCLUDED.source_monograph,
    source_section = EXCLUDED.source_section,
    evidence_excerpt = EXCLUDED.evidence_excerpt,
    verified = EXCLUDED.verified,
    active = EXCLUDED.active,
    updated_at = NOW();
