-- Seed: seed_verified_videos.sql
-- Description: Verified Arabic Instructional Videos (Deutsche Atemwegsliga, MSD Manual Arabic, Saudi MOH)

INSERT INTO public.verified_videos (
    title, usage_topic, category, dosage_form, device_type, device_name, aliases, language, video_url, thumbnail_url, source_name, source_url, source_tier, verified, active, verification_notes
) VALUES
-- 1. AeroChamber
(
    'طريقة استخدام جهاز حجرة الاستنشاق (AeroChamber)',
    'aerochamber_usage',
    'inhaler',
    'inhalation',
    'spacer',
    'AeroChamber',
    ARRAY['aerochamber', 'ايروشمبر', 'حجرة الاستنشاق', 'سبيسر ايروشمبر'],
    'ar',
    'https://youtu.be/wtSw3U9cz0M',
    'https://img.youtube.com/vi/wtSw3U9cz0M/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 2. Autohaler
(
    'طريقة استخدام بخاخ الأوتوهيلر (Autohaler)',
    'autohaler_usage',
    'inhaler',
    'inhalation',
    'breath_actuated_MDI',
    'Autohaler',
    ARRAY['autohaler', 'اوتوهيلر', 'اوتوهيلار'],
    'ar',
    'https://youtu.be/6SxnAJWAJBg',
    'https://img.youtube.com/vi/6SxnAJWAJBg/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 3. Breezhaler Mono
(
    'طريقة استخدام بخاخ البريزهيلر أحادي المادة (Breezhaler)',
    'breezhaler_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Breezhaler',
    ARRAY['breezhaler', 'بريزهيلر', 'اونبريز'],
    'ar',
    'https://youtu.be/P16vS8_4HqE',
    'https://img.youtube.com/vi/P16vS8_4HqE/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 4. Breezhaler Combination
(
    'طريقة استخدام بخاخ البريزهيلر المركب (Breezhaler Combination)',
    'breezhaler_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Breezhaler',
    ARRAY['breezhaler combination', 'بريزهيلر مركب', 'التيريز'],
    'ar',
    'https://youtu.be/K_l5-9bsASc',
    'https://img.youtube.com/vi/K_l5-9bsASc/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 5. Diskus / Accuhaler
(
    'طريقة استخدام بخاخ الديسكوس / أكيوهيلر (Diskus / Accuhaler)',
    'diskus_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Diskus',
    ARRAY['diskus', 'accuhaler', 'ديسكوس', 'اكيوهيلر', 'أكيوهيلر', 'سيريتيد'],
    'ar',
    'https://youtu.be/gPanzwWilYg',
    'https://img.youtube.com/vi/gPanzwWilYg/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 6. pMDI / Metered Dose Inhaler (Primary: Deutsche Atemwegsliga)
(
    'طريقة استخدام بخاخ الجرعات المقننة المضغوط (pMDI / Metered Dose Inhaler)',
    'pmdi_usage',
    'inhaler',
    'inhalation',
    'pMDI',
    'pMDI',
    ARRAY['pmdi', 'metered dose inhaler', 'evohaler', 'بخاخ الربو المضغوط', 'بخاخ مضغوط', 'جرعات مقننة', 'ايفوهيلر', 'فنتولين بخاخ'],
    'ar',
    'https://youtu.be/y4KmmNuaBFo',
    'https://img.youtube.com/vi/y4KmmNuaBFo/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 7. pMDI Fallback (MSD Manual Arabic)
(
    'طريقة استعمال أجهزة الاستنشاق بالجرعات المقننة',
    'pmdi_usage',
    'inhaler',
    'inhalation',
    'pMDI',
    'pMDI',
    ARRAY['pmdi msd', 'استنشاق جرعات مقننة msd'],
    'ar',
    'https://www.msdmanuals.com/ar/home/multimedia/video/طريقة-استعمال-أجهزة-الاستنشاق-بالجرعات-المقننة',
    'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    'MSD Manual Arabic',
    'https://www.msdmanuals.com/ar',
    'B_recognized_medical_organization',
    true,
    true,
    'Verified educational video by MSD Manual Arabic.'
),
-- 8. Ellipta
(
    'طريقة استخدام بخاخ الإليبيتا (Ellipta)',
    'ellipta_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Ellipta',
    ARRAY['ellipta', 'اليبيتا', 'إليبتَا', 'ريلفار إليبيتا', 'تريليجي'],
    'ar',
    'https://youtu.be/F7YWhnNFdnQ',
    'https://img.youtube.com/vi/F7YWhnNFdnQ/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 9. Forspiro
(
    'طريقة استخدام بخاخ فورسبييرو (Forspiro)',
    'forspiro_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Forspiro',
    ARRAY['forspiro', 'فورسبييرو', 'فورسبيرو'],
    'ar',
    'https://youtu.be/y94Gi8XxQQU',
    'https://img.youtube.com/vi/y94Gi8XxQQU/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 10. Genuair
(
    'طريقة استخدام بخاخ جينواير (Genuair)',
    'genuair_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Genuair',
    ARRAY['genuair', 'جينواير'],
    'ar',
    'https://youtu.be/xMD9HpAmEgk',
    'https://img.youtube.com/vi/xMD9HpAmEgk/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 11. HandiHaler
(
    'طريقة استخدام بخاخ الهاندي هيلر (HandiHaler)',
    'handihaler_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'HandiHaler',
    ARRAY['handihaler', 'هاندي هيلر', 'هانديهيلر', 'سبيريفا كبسول'],
    'ar',
    'https://youtu.be/ptO0aIGLSRY',
    'https://img.youtube.com/vi/ptO0aIGLSRY/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 12. NEXThaler
(
    'طريقة استخدام بخاخ نكست هيلر (NEXThaler)',
    'nexthaler_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'NEXThaler',
    ARRAY['nexthaler', 'نكست هيلر', 'نكستهيلر'],
    'ar',
    'https://youtu.be/Ur_grKNKuNQ',
    'https://img.youtube.com/vi/Ur_grKNKuNQ/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 13. Novolizer
(
    'طريقة استخدام بخاخ نوفولايزر (Novolizer)',
    'novolizer_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Novolizer',
    ARRAY['novolizer', 'نوفولايزر', 'نوفوليزر'],
    'ar',
    'https://youtu.be/wHu8o5fiOqA',
    'https://img.youtube.com/vi/wHu8o5fiOqA/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 14. Respimat
(
    'طريقة استخدام بخاخ الريسبيمات (Respimat)',
    'respimat_usage',
    'inhaler',
    'inhalation',
    'SMI',
    'Respimat',
    ARRAY['respimat', 'ريسبيمات', 'سبيريفا ريسبيمات'],
    'ar',
    'https://youtu.be/6wNDQfeZEX4',
    'https://img.youtube.com/vi/6wNDQfeZEX4/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 15. Turbohaler
(
    'طريقة استخدام بخاخ التربوهيلر (Turbohaler)',
    'turbohaler_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Turbohaler',
    ARRAY['turbohaler', 'turbuhaler', 'تربوهيلر', 'تيربوهيلر', 'سيمبيكورت تربوهيلر'],
    'ar',
    'https://youtu.be/Xnk8oYQPbaw',
    'https://img.youtube.com/vi/Xnk8oYQPbaw/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 16. Spiromax
(
    'طريقة استخدام بخاخ سبايروماكس (Spiromax)',
    'spiromax_usage',
    'inhaler',
    'inhalation',
    'DPI',
    'Spiromax',
    ARRAY['spiromax', 'سبايروماكس', 'سبيروماكس'],
    'ar',
    'https://youtu.be/ebestHd2r08',
    'https://img.youtube.com/vi/ebestHd2r08/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 17. Vortex
(
    'طريقة استخدام حجرة الاستنشاق فورتكس (Vortex Spacer)',
    'vortex_spacer_usage',
    'inhaler',
    'inhalation',
    'spacer',
    'Vortex',
    ARRAY['vortex', 'فورتكس', 'فورتكس سبيسر'],
    'ar',
    'https://youtu.be/6a-IO2THEaA',
    'https://img.youtube.com/vi/6a-IO2THEaA/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video by Deutsche Atemwegsliga e.V.'
),
-- 18. PARI BOY (Strictly Device-Specific; NEVER Generic Nebulizer)
(
    'طريقة استخدام جهاز نيبولايزر باري بوي (PARI BOY Nebulizer)',
    'pari_boy_nebulizer_usage',
    'nebulizer',
    'inhalation',
    'nebulizer',
    'PARI BOY',
    ARRAY['pari boy', 'باري بوي', 'باري بوي نيبولايزر', 'pari boy nebulizer'],
    'ar',
    'https://youtu.be/sGg9Xkv4rnI',
    'https://img.youtube.com/vi/sGg9Xkv4rnI/hqdefault.jpg',
    'Deutsche Atemwegsliga e.V.',
    'https://www.atemwegsliga.de/richtig-inhalieren/zu-den-videos-international/arabisch.html',
    'B_recognized_medical_organization',
    true,
    true,
    'Official Arabic video for PARI BOY device only.'
),
-- 19. Insulin Pen (Saudi Ministry of Health)
(
    'طريقة استخدام قلم الأنسولين',
    'insulin_pen_usage',
    'insulin_injection',
    'subcutaneous_injection',
    'pen_injector',
    'Generic Insulin Pen',
    ARRAY['insulin pen', 'قلم انسولين', 'قلم الانسولين', 'حقن الانسولين بالقلم'],
    'ar',
    'https://www.youtube.com/watch?v=7SLD3YQtNoE',
    'https://img.youtube.com/vi/7SLD3YQtNoE/hqdefault.jpg',
    'وزارة الصحة السعودية',
    'https://www.moh.gov.sa',
    'B_government_health_authority',
    true,
    true,
    'Official Arabic instructional video by Saudi Ministry of Health.'
)
ON CONFLICT (id) DO NOTHING;
